version: '3.1'
services:
  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root1111
      - MYSQL_DATABASE=blog_project
  app:
    container_name: blogbackend2
    image: blogbackend2:latest
    restart: always
    build: .
    ports:
      - "1111:1111"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/blog_project?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb