version: '3.1'
services:
  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root1111
      - MYSQL_DATABASE=blog_project
  backend:
    container_name: blogbackend2
    image: blogbackend2:latest
    restart: always
    build: .
    ports:
      - "1111:1111"
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/blog_project?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
  postgresqldb:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=techcareerairtiesgateway
  backendmicro:
    container_name: blogauth
    image: blogauth:latest
    restart: always
    build: .
    ports:
      - "3333:3333"
    environment:
      - spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/techcareerairtiesgateway?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - postgresqldb
      